apiVersion: v1
kind: Service
metadata:
  name: reference-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reference-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
